### ISSUE TITLE
Implement std::error::Error for error type(s).

### ISSUE THREAD

**Issue by cheako** [gwihlidal/vk-mem-rs#17]
I'm trying to use crate snafu, but it's unable to work with types that don't implement it.

**Comment by aloucks** [comment]
If you disable the "failure" feature `std::error::Error` is implemented for the Error struct.

https://github.com/gwihlidal/vk-mem-rs/blob/c9a463bcc31607a4a45394c7889fb1db8a2a6403/src/error.rs#L73-L81

**Comment by gwihlidal** [comment]
Failure is now disabled by default.
