### ISSUE TITLE
`Allocator::clone` causes multiple `vmaDestroyAllocator` calls

### ISSUE THREAD

**Issue by Friz64** [gwihlidal/vk-mem-rs#18]
`Allocator::clone` causes a double free because it allows the `Allocator` object to be dropped multiple times.

#### Example

```rust
let harness = TestHarness::new();
let x = harness.create_allocator();
let y = x.clone();
```

#### What happens

- Allocator X gets cloned to Allocator Y, including its pointer to the underlying ffi Allocator `self.internal`.
- Allocator Y gets dropped, its cloned pointer to `self.internal` is not null so it calls `vmaDestroyAllocator` on it.
- Allocator X gets dropped, its own pointer to `self.internal` wasn't modified so it also calls `vmaDestroyAllocator` on it.

💥 Segfault!

#### Possible solutions

- Remove the ability to clone `Allocator`
- Use reference counting (?)

**Comment by aloucks** [comment]
Removing `Clone` makes the most sense to me. The `destroy` method is the only one left that takes `&mut self`. Wrapping the `Allocator` in an `Arc` shouldn't pose any issue now if you still need to clone it.

**Comment by Friz64** [comment]
For now wrapping it in an `Arc` is not the most optimal solution because some methods require a mutable reference, which would result in an unneeded `Mutex`. I have personally solved it by using `std::mem::ManuallyDrop`.

**Comment by aloucks** [comment]
> because some methods (`map_memory`, ..) require a mutable reference

[That was recently changed](https://github.com/gwihlidal/vk-mem-rs/pull/16). They all take `&self` now.

**Comment by Friz64** [comment]
Oh, okay! I have been using the crates.io version of this crate, thank you for the clarification.
