### ISSUE TITLE
Parameter for counting bytes size should be `ffi::VkDeviceSize` type

### ISSUE THREAD

**Issue by unknownue** [gwihlidal/vk-mem-rs#21]
In vulkan, we use `VkDeviceSize` to represent the size and offset value of memory in bytes.
```c++
typedef uint64_t VkDeviceSize;
```
However some functions in this crate receive `usize` instead of `ash::vk::DeviceSize` as parameters.
The `flush_allocation` method is one of them.
```rust
// This function internally casts `usize` to `ash::vk::DeviceSize`.
pub fn flush_allocation(&self, allocation: &Allocation, offset: usize, size: usize) -> Result<()> {
    unsafe {
        ffi::vmaFlushAllocation(self.internal, allocation.internal, offset as ffi::VkDeviceSize, size as ffi::VkDeviceSize);
    }
    Ok(())
}
```
I generally use the `ash::vk::DeviceSize` type to store and pass value to vulkan api, which may cause unnecessary type casting between `usize` and `ash::vk::DeviceSize`. For example:
```rust
struct CustomBuffer {
    handle: ash::vk::Buffer,
    allocation: vk_mem::Allocation,
    size: ash::vk::DeviceSize,
}

let (handle, allocation, alloc_info) = allocator.create_buffer(...);
let mybuffer = CustomBuffer { handle, allocation, size }; 
...
allocator.flush_allocation(&allocation, 0_usize, mybuffer.size as usize);
```
In this above snippet, the call to `flush_allocation` incurs unnecessary type casting for twice(one in `mybuffer.size as usize`, another in `size as ffi::VkDeviceSize`).

Since `vk::DeviceSize` is used through out `ash` crate, I think it's better to be consistent with `ash` and replace the `usize` parameters with `ash::vk::DeviceSize`.

This will cause API change in methods include `flush_allocation()`, `invalidate_allocation()`, `resize_allocation()` and struct definition include `DefragmentationInfo`, `AllocatorPoolCreateInfo`.
I am willing to create a PR for this problem.

**Comment by gwihlidal** [comment]
I'm willing to look at a PR for this if you want to make it.

**Comment by gwihlidal** [comment]
Closed as per comments in PR
