### ISSUE TITLE
0.2.1 is a breaking update

### ISSUE THREAD

**Issue by LaylConway** [gwihlidal/vk-mem-rs#29]
Some values' types got changed, this broke existing code.
It might be better to yank it and upload it at 0.3.0.

**Comment by LaylConway** [comment]
Actually I was mistaken, the update's not just breaking existing code, it's internally not building.

**Comment by brandonpollack23** [comment]
I'm working on a fix now, I've updated a bunch of stuff in lib.rs to size_t, but there's one more problem caused by version mismatching between ash and FFI im looking into

**Comment by gwihlidal** [comment]
Thank you - these issues weren't caught on my OSX build/test, but breaks on Windows. I also made the size_t fixes now, but I'll let you submit the PR @brandonpollack23 if you're working on that last FFI issue. Afterwards I'll push a new version right away!

**Comment by aloucks** [comment]
The range version specify on the `ash` dependency also causes breakage because ash is part of the public interface of vk-mem. It would be better to use a fixed version and release a new vk-mem whenever ash has a non-patch release.

**Comment by aloucks** [comment]
Alternately, ash could be removed from the public interface, but that's a bigger effort/conversation.

**Comment by brandonpollack23** [comment]
Almost done...just trying to find the source of the difference since the version in vendor seems to be up to date and the same...

**Comment by gwihlidal** [comment]
Hmm, I have heard of others (like Embark) successfully relying on the >= version specifier (ash = ">= 0.27.1")

**Comment by brandonpollack23** [comment]
In order to speed this up I'll take any hints I can get.  The ash PhysicalDeviceProperties is 8 bytes larger than the one in ffi::vkPhysicalDeviceProperties

**Comment by brandonpollack23** [comment]
Things I've looked into:

Copying latest SDK headers into wrapper/ directory
cleaning and rebuilding after doing that

**Comment by gwihlidal** [comment]
Arg, it seems like the difference is between vk::PhysicalDeviceLimits and ffi::VkPhysicalDeviceLimits - i.e. `min_memory_map_alignment: usize` vs `minMemoryMapAlignment: size_t`.

**Comment by aloucks** [comment]
> Hmm, I have heard of others (like Embark) successfully relying on the >= version specifier (ash = ">= 0.27.1")

I believe the only way is to commit `Cargo.lock` to your git, which isn't recommended for libraries. It still breaks if you do a `cargo update` though. However, I'm curious if they've found another workaround.

**Comment by brandonpollack23** [comment]
@gwihlidal Manually modifying the file to have a usize instead of size_t gets me a compile...but this is a generated file so that isn't viable.  Should we PR into ash to change to size_t...shouldn't those be teh same size anyway???

**Comment by aloucks** [comment]
VkDeviceSize is u64, I believe.

**Comment by gwihlidal** [comment]
@brandonpollack23 It seems like VMA changed this type (why, I don't know), and ash needs to regenerate.

**Comment by gwihlidal** [comment]
@aloucks yes, VkDeviceSize is always u64, whereas size_t is variable

**Comment by brandonpollack23** [comment]
@aloucks indeed it is

**Comment by brandonpollack23** [comment]
cool well I'll PR in the size_t changes for now

**Comment by brandonpollack23** [comment]
@gwihlidal not vma, vulkan, yes?

**Comment by gwihlidal** [comment]
right, I misspoke

**Comment by gwihlidal** [comment]
It seems like an error, all the other size/alignments are VkDeviceSize (always u64), but this field is size_t here: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceLimits.html

**Comment by brandonpollack23** [comment]
shouldn't it be size_t since its not relevant to device size, but host side mmap alignment?

**Comment by brandonpollack23** [comment]
I think this ield is a red herring now, it may be somethign else

**Comment by gwihlidal** [comment]
Yeah, I think so too. Both usize and size_t should match on the appropriate 32 or 64 bit target

**Comment by brandonpollack23** [comment]
Ok how's this for a theory:

bindings.rs defines size_t on my platform as:
pub type size_t = ::std::os::raw::c_ulong;

according to the [docs](https://doc.rust-lang.org/std/os/raw/type.c_ulong.html) this varies based on OS, not pointer size.

so if we change this line to pub type size_t = usize it all compiles and makes sense

**Comment by gwihlidal** [comment]
Yeah, so that would likely explain the other changes needed after I upgraded - a bit weird for the problems to start happening, but maybe a newer bindgen is doing something weird.

**Comment by gwihlidal** [comment]
This new bindgen seems to no longer use `usize` for `size_t`, it instead does (what you mentioned) of `pub type size_t = ::std::os::raw::c_ulong;`

**Comment by brandonpollack23** [comment]
https://github.com/rust-lang/rust-bindgen/pull/1688/files is the PR in question

**Comment by brandonpollack23** [comment]
the issue I think is that the bindgen is behind a feature, but should be generated on every platform now.

Either that or is there a way to configure bindgen to add in #[cfg(platform)] flags for us

**Comment by gwihlidal** [comment]
I think I figured it out, mind checking on your end for me please? https://github.com/gwihlidal/vk-mem-rs/commit/d75b9b137a98f9cd2e4e41b7c2dcd3424a90e1a1

That PR was helpful, I found the previous behaviour was moved behind a switch, so I was able to set that and remove all recent size changes. I actually think the new bindgen behaviour is completely incorrect, as size_t should never be u32 on a 64 bit Windows target.

**Comment by brandonpollack23** [comment]
I actually just got it, we tied!!!

We need to remove the generate_bindings feature and let windows generate its own bindings without being behind a feature flag b/c different platforms generate bindings diffferently, so that other PR is also no longer needed

**Comment by aloucks** [comment]
> We need to remove the generate_bindings feature and let windows generate its own bindings without being behind a feature flag

Won't that add an external dependency on having clang installed?

**Comment by gwihlidal** [comment]
Yeah, I don't want that, the whole point of the feature is to not have a requirement on clang (which is a very heavy requirement).

**Comment by gwihlidal** [comment]
size_t being 32bit on a 64bit Windows machine is baaaaaad. Any larger than 2GB sizes/offsets would be broken. Bindgen is broken, but at least this flag restores the sane behaviour.

**Comment by brandonpollack23** [comment]
Ill throw up the PR so its an option for whatever you decide to do, but perhaps the best bet would be looping in the rust team/bindgen folks and seeing what they advise

**Comment by gwihlidal** [comment]
Thanks for all the help everyone - I'll push a new version in a bit once I test it further on my Windows machine.

**Comment by brandonpollack23** [comment]
Just tested out your commit, that works !!!

**Comment by brandonpollack23** [comment]
Would it be a lot of trouble to have the CI system (new to contributing to github) run with generate_bindings on windows as well so PRs cant go in that would break like this?

**Comment by gwihlidal** [comment]
> Would it be a lot of trouble to have the CI system (new to contributing to github) run with generate_bindings on windows as well so PRs cant go in that would break like this?

I have updated the build script to require the Windows build in order to pass.

**Comment by gwihlidal** [comment]
I have fixed the issues and published 0.2.2 - thanks for the assistance!
