### ISSUE TITLE
Consider deriving more traits for opaque pointers.

### ISSUE THREAD

**Issue by cheako** [gwihlidal/vk-mem-rs#34]
I'm *adding the traits ash supports namely ```Eq, PartialEq, Ord, PartialOrd, Hash```.

I wanted to use an ImageView as a hash key and I needed these traits.  Thought I can't see a reason why this would apply to vk_mem, it's still something to consider.

Thanks.

* To my ash-tray vk_helper module.

**Comment by Neo-Zhixing** [comment]
This is perhaps a better issue in the ash crate?
