### ISSUE TITLE
Error in Default for AllocatorCreateInfo

### ISSUE THREAD

**Issue by pmathia0** [gwihlidal/vk-mem-rs#42]
rust 1.46.0 works fine 
```
 let allocator_info = vk_mem::AllocatorCreateInfo {
            physical_device: base._gpu.unwrap(),
            device: device.clone(),
            instance: base.instance.clone(),
            frame_in_use_count: 2u32,
            ..Default::default()
};
```
latest rust 1.48.0 fails: attempted to zero-initialize type `ash::Device`, which is invalid
specifying all fields in allocator_info and avoiding default solves the problem, so I suppose somethings wrong in default implementation
vk_mem 0.2.2
ash 0.31.0
Windows 10

**Comment by aloucks** [comment]
It's fixed in #39 but there has not yet been a new release.

**Comment by gwihlidal** [comment]
Thanks - I've been incredibly busy lately and I'd like to push a new release with all of this, but master doesn't seem to be building right now. If someone could fix it I could push a release, or it'll need to wait until I can find some time to look into it.

**Comment by hoj-senna** [comment]
Many thanks for the fix, and for vk-mem-rs in the first place.

> but master doesn't seem to be building right now. 

I was able to avoid this building problem by changing '#define VMA_DYNAMIC_VULKAN_FUNCTIONS 1' to '#define VMA_DYNAMIC_VULKAN_FUNCTIONS 0' in line 4021 of vk_mem_alloc.h. — That file is part of VulkanMemoryAllocator, not of vk-mem-rs; and I don't know what/how much this change would break. (I just wanted to mention it in case this helps.)

**Comment by matthewjberger** [comment]
@hoj-senna We can achieve that by adding

```
build.define("VMA_DYNAMIC_VULKAN_FUNCTIONS", "0");
```

to the `build.rs` in this repo
