### ISSUE TITLE
allocation_info.get_mapped_data() returns null for mapped buffer

### ISSUE THREAD

**Issue by aclysma** [gwihlidal/vk-mem-rs#43]
If I run this code:

```rust
        let buffer_info = ash::vk::BufferCreateInfo::builder()
            .size(1024)
            .usage(ash::vk::BufferUsageFlags::VERTEX_BUFFER)
            .sharing_mode(ash::vk::SharingMode::EXCLUSIVE)
            .build();

        let alloc_info = vk_mem::AllocationCreateInfo {
            usage: vk_mem::MemoryUsage::CpuOnly,
            ..Default::default()
        };

        let (buffer, allocation, allocation_info) = allocator.create_buffer(
            &buffer_info, 
            &alloc_info
        )?;

        let map_memory_result = allocator.map_memory(&allocation).unwrap();
        let get_mapped_data_result = allocation_info.get_mapped_data();
        println!("map_memory_result {:?}", map_memory_result);
        println!("get_mapped_data_result {:?}", get_mapped_data_result);
```

It prints:

```
map_memory_result 0x113434000
get_mapped_data_result 0x0
```

The documentation for get_mapped_data states:
> "If the allocation hasn't been mapped using `Allocator::map_memory` and hasn't been created with `AllocationCreateFlags::MAPPED` flag, this value is null."

Based on the comment, I expected get_mapped_data() would return a valid pointer in this case.

It returns a valid pointer if adding vk_mem::AllocationCreateFlags::MAPPED to the allocation info.

Any ideas? Thanks for maintaining these bindings!

**Comment by aloucks** [comment]
> > "If the allocation hasn't been mapped using `Allocator::map_memory` and hasn't been created with `AllocationCreateFlags::MAPPED` flag, this value is null."
> 
> Based on the comment, I expected get_mapped_data() would return a valid pointer in this case.
>
> It returns a valid pointer if adding vk_mem::AllocationCreateFlags::MAPPED to the allocation info.

You're observed behavior matches the documented behavior. You're calling `get_mapped_data()` on the `allocation_info` that was created _before_ you  mapped the memory. Try fetching a fresh copy of the `AllocationInfo` with [get_allocation_info](https://docs.rs/vk-mem/0.2.2/vk_mem/struct.Allocator.html#method.get_allocation_info) after you map it.

**Comment by aclysma** [comment]
Thanks, that sounds like a very likely explanation, will try it again soon!

**Comment by aclysma** [comment]
Thanks, that was it!
