### ISSUE TITLE
0.2.3 release

### ISSUE THREAD

**Issue by michidk** [gwihlidal/vk-mem-rs#46]
Hi,

I just saw you bumped the version. I wonder when it gets released on crates.io?

**Comment by michidk** [comment]
Also the readme states, that ```[dependencies]
vk-mem = "0.2.3"``` shall be used, which cannot work, since the version is not released on crates.io. What works is 
```
vk-mem = { git = "https://github.com/gwihlidal/vk-mem-rs", version = "0.2.3" }
```

**Comment by Neo-Zhixing** [comment]
Closed by https://github.com/gwihlidal/vk-mem-rs/pull/66
