### ISSUE TITLE
Strange default flags on AllocationCreateInfo

### ISSUE THREAD

**Issue by duodenim** [gwihlidal/vk-mem-rs#5]
The default trait implementation of AllocationCreateInfo adds DEVICE_LOCAL in the list of required flags of an allocation. This makes it impossible to create a CPU visible buffer using the usage parameter without also overriding required_flags.

**Comment by LaylConway** [comment]
I've fixed this in https://github.com/gwihlidal/vk-mem-rs/pull/4

**Comment by gwihlidal** [comment]
Thanks, will merge and release
