### ISSUE TITLE
Missing `vulkan/vulkan.h` and `__popcnt` on x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by James2022-rgb** [gwihlidal/vk-mem-rs#60]
Just wanted to note that when trying to build for `x86_64-pc-windows-msvc`, `cl.exe`
- failed to find "vulkan/vulkan.h"
- failed to find the identifier `__popcnt` at `vk_mem_alloc.h` L3068

I worked around the first one by changing
https://github.com/gwihlidal/vk-mem-rs/blob/0be89847669f4258c0de790fb49981dbd4c2af25/build.rs#L11
to `build.include("vendor/Vulkan-Headers/include")`, though I don't know if this is really the correct way.

The second one was apparently fixed on https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/b41615cfce1bc895b3ead88baa69c7ca345def51,
so pulling the latest `master` commit in the submodule was enough,
though `__popcnt` does not seem to be used anymore anyway.

**Comment by Neo-Zhixing** [comment]
Should be fixed now. If not, feel free to open a new issue.
