### ISSUE TITLE
Fork created with updated VMA version and most pending PRs merged

### ISSUE THREAD

**Issue by Neo-Zhixing** [gwihlidal/vk-mem-rs#64]
The `vk-mem-rs` project has been experiencing a lack of maintenance activity. Last year, #62 was merged without reviews which broke the tests and caused build failures. The original author  @gwihlidal seems to have been busy and did not respond to my emails. So to address this issue and ensure the project remains active and useful, a new fork of `vk-mem-rs` has been created under the `dust-engine` organization. The new fork has up-to-date dependencies and has merged #63 which fixed the build failure alongside other improvements. The purpose of this fork is to provide an actively maintained version of `vk-mem-rs` that incorporates the latest community contributions and resolves any outstanding issues.

We invite the community to join us in the new fork of `vk-mem-rs`. Your contributions, feedback, and assistance in reviewing and merging PRs will be greatly appreciated.

Repository Link: [dust-engine/vk-mem-rs](https://github.com/dust-engine/vk-mem-rs)
crates.io Link: [vma](https://crates.io/crates/vma)

**Comment by MarijnS95** [comment]
There is also [`gpu-allocator`](https://github.com/Traverse-Research/gpu-allocator/) which implements the allocation algorithms and business logic for Vulkan and DirectX12 directly in rust :grinning:

**Comment by Neo-Zhixing** [comment]
@MarijnS95
Thanks! I'm aware of the `gpu-allocator` project but it's lacking certain features that we need, like defragmentation, memory pools and virtual memory blocks. I will continue to maintain the vk-mem-rs project until `gpu-allocator` reaches feature parity.

**Comment by gwihlidal** [comment]
Hey @Neo-Zhixing - apologies for such a late reply - I've been absolutely swamped, and no time for rust sadly (at least right now). I'd be willing to give you co-ownership of this repo instead of maintaining a fork if you are open to that.

**Comment by Neo-Zhixing** [comment]
@gwihlidal That'd be great! Please also add me to crates.io so that I can publish new versions.

**Comment by bkolligs** [comment]
@Neo-Zhixing which repository are you actively maintaining? I'm looking to use _some_ binding to VMA

**Comment by Neo-Zhixing** [comment]
@bkolligs I'm still maintaining the forked repo since @gwihlidal did not actually give me co-ownership

https://github.com/dust-engine/vk-mem-rs

**Comment by Neo-Zhixing** [comment]
With #66 the fork is no longer being maintained. I have updated this repo & published the latest changes to cargo.
